name: Deploy Jekyll site to GitHub Pages

on:
  # Executa em pushes para a branch especificada (geralmente main ou master)
  push:
    branches:
      - main # Mude para 'master' se essa for sua branch principal
  
  # Permite que você execute este workflow manualmente a partir da aba Actions no GitHub
  workflow_dispatch:

# Define permissões para o GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, pulando execuções enfileiradas entre a em progresso e a mais recente.
# No entanto, NÃO cancela execuções em progresso, pois queremos permitir que esses deploys de produção sejam concluídos.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Pages
        id: pages # Adicionado id para referência futura se necessário
        uses: actions/configure-pages@v5
      
      - name: Build with Jekyll
        # Esta Action oficial constrói seu site Jekyll
        # e lida automaticamente com a configuração do baseurl para GitHub Pages.
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./site # <--- IMPORTANTE: Especifica que seu site Jekyll está na pasta 'site'
          destination: ./_site # O local padrão onde o site construído será colocado (relativo à raiz do workspace)
      
      - name: Upload artifact
        # Esta Action faz o upload do site construído para que o job de deploy possa usá-lo
        uses: actions/upload-pages-artifact@v3
        # Por padrão, ele pega o conteúdo de '_site' na raiz do workspace, 
        # que é onde 'actions/jekyll-build-pages' coloca o resultado.

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Garante que o job de build foi concluído com sucesso primeiro
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Esta Action publica o artefato no GitHub Pages
